### PR TITLE
use runtime paths

### PR DESCRIPTION
**Pull request by mbutterick**

### CODE REVIEW

**Comment by mbutterick** [comment]
The `setup` module, when shared by multiple project directories, is evaluated separately for each directory and **relative to that directory**. So when you have relative pathnames, as you do here, they are expanded to complete paths as if they were in those directories. 

Sometimes this is what you want — for instance, suppose you have a `"foobar.rkt"` in every directory, and want the cache for each directory to watch the `"foobar.rkt"` in that particular directory. 

But here, you want the opposite behavior — every subdirectory using the same global files for its watchlist. In that case, you need to nail down the absolute paths right away with `define-runtime-path`.

**Comment by mbutterick** [comment]
The cache, of course, uses the watchlist files as part of the key for the cached value. If a certain file is missing, however, it doesn’t complain. Maybe this is a bad policy — it would’ve caught this error, at least. But given that the cache is supposed to be unobtrusive, it has seemed to me that it should be as quiet and lenient as possible, especially given that it doesn’t actually read the contents of the files.

**Comment by otherjoel** [comment]
This is a huge performance improvement. I originally did some hasty cut/paste from an older version of the Pollen docs without really reading to understand the underlying functions. Going to do some more reading for sure. 

I do like that the cache is unobtrusive. But for _missing_ files on the watchlist, I am guessing it would be better to have a warning. I can't think of a case where an author has a) kept the cache enabled, b) added files to the watchlist and c) doesn't want to know if the cache is continuously missing because of an absent file. Especially since the absent file is (likely) never going to materialize as a result of the render.

Thanks for the PR and comments! You have likely added several hours to my life.

**Comment by mbutterick** [comment]
OK. I just pushed a fix so the cache will issue a warning message (but not an error) if a `cache-watchlist` file is missing.

**Pull request merged**
